//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MCSharp.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MCSharpParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IMCSharpListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] MCSharpParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] MCSharpParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_parameter([NotNull] MCSharpParser.Generic_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_parameter([NotNull] MCSharpParser.Generic_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_parameter_list([NotNull] MCSharpParser.Generic_parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_parameter_list([NotNull] MCSharpParser.Generic_parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_parameters([NotNull] MCSharpParser.Generic_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_parameters([NotNull] MCSharpParser.Generic_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_parameter([NotNull] MCSharpParser.Method_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_parameter([NotNull] MCSharpParser.Method_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_parameter_list([NotNull] MCSharpParser.Method_parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_parameter_list([NotNull] MCSharpParser.Method_parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_parameters([NotNull] MCSharpParser.Method_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_parameters([NotNull] MCSharpParser.Method_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.indexer_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexer_parameters([NotNull] MCSharpParser.Indexer_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.indexer_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexer_parameters([NotNull] MCSharpParser.Indexer_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] MCSharpParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] MCSharpParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_list([NotNull] MCSharpParser.Argument_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_list([NotNull] MCSharpParser.Argument_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_arguments([NotNull] MCSharpParser.Generic_argumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_arguments([NotNull] MCSharpParser.Generic_argumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_arguments([NotNull] MCSharpParser.Method_argumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_arguments([NotNull] MCSharpParser.Method_argumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.indexer_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexer_arguments([NotNull] MCSharpParser.Indexer_argumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.indexer_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexer_arguments([NotNull] MCSharpParser.Indexer_argumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.member_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_initializer([NotNull] MCSharpParser.Member_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.member_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_initializer([NotNull] MCSharpParser.Member_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_initializer([NotNull] MCSharpParser.Object_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_initializer([NotNull] MCSharpParser.Object_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement_initializer([NotNull] MCSharpParser.Element_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement_initializer([NotNull] MCSharpParser.Element_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollection_initializer([NotNull] MCSharpParser.Collection_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollection_initializer([NotNull] MCSharpParser.Collection_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.anonymous_element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnonymous_element_initializer([NotNull] MCSharpParser.Anonymous_element_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.anonymous_element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnonymous_element_initializer([NotNull] MCSharpParser.Anonymous_element_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.anonymous_object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnonymous_object_initializer([NotNull] MCSharpParser.Anonymous_object_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.anonymous_object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnonymous_object_initializer([NotNull] MCSharpParser.Anonymous_object_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] MCSharpParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] MCSharpParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.parameter_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_modifier([NotNull] MCSharpParser.Parameter_modifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.parameter_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_modifier([NotNull] MCSharpParser.Parameter_modifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_type([NotNull] MCSharpParser.Class_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_type([NotNull] MCSharpParser.Class_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_definition([NotNull] MCSharpParser.Type_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_definition([NotNull] MCSharpParser.Type_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.member_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_definition([NotNull] MCSharpParser.Member_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.member_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_definition([NotNull] MCSharpParser.Member_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.constructor_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructor_definition([NotNull] MCSharpParser.Constructor_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.constructor_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructor_definition([NotNull] MCSharpParser.Constructor_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.field_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_definition([NotNull] MCSharpParser.Field_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.field_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_definition([NotNull] MCSharpParser.Field_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.property_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_definition([NotNull] MCSharpParser.Property_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.property_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_definition([NotNull] MCSharpParser.Property_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.property_get_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_get_definition([NotNull] MCSharpParser.Property_get_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.property_get_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_get_definition([NotNull] MCSharpParser.Property_get_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.property_set_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_set_definition([NotNull] MCSharpParser.Property_set_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.property_set_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_set_definition([NotNull] MCSharpParser.Property_set_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_definition([NotNull] MCSharpParser.Method_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_definition([NotNull] MCSharpParser.Method_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] MCSharpParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] MCSharpParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] MCSharpParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] MCSharpParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MCSharpParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MCSharpParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.code_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode_block([NotNull] MCSharpParser.Code_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.code_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode_block([NotNull] MCSharpParser.Code_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.additive_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditive_operator([NotNull] MCSharpParser.Additive_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.additive_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditive_operator([NotNull] MCSharpParser.Additive_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.multiplicative_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicative_operator([NotNull] MCSharpParser.Multiplicative_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.multiplicative_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicative_operator([NotNull] MCSharpParser.Multiplicative_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.step_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStep_operator([NotNull] MCSharpParser.Step_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.step_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStep_operator([NotNull] MCSharpParser.Step_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.bitwise_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwise_operator([NotNull] MCSharpParser.Bitwise_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.bitwise_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwise_operator([NotNull] MCSharpParser.Bitwise_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.boolean_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_operator([NotNull] MCSharpParser.Boolean_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.boolean_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_operator([NotNull] MCSharpParser.Boolean_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_operator([NotNull] MCSharpParser.Shift_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_operator([NotNull] MCSharpParser.Shift_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.equality_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality_operator([NotNull] MCSharpParser.Equality_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.equality_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality_operator([NotNull] MCSharpParser.Equality_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.relation_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelation_operator([NotNull] MCSharpParser.Relation_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.relation_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelation_operator([NotNull] MCSharpParser.Relation_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] MCSharpParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] MCSharpParser.Assignment_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.range_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange_operator([NotNull] MCSharpParser.Range_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.range_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange_operator([NotNull] MCSharpParser.Range_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.language_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLanguage_function([NotNull] MCSharpParser.Language_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.language_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLanguage_function([NotNull] MCSharpParser.Language_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] MCSharpParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] MCSharpParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_statement([NotNull] MCSharpParser.For_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_statement([NotNull] MCSharpParser.For_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.foreach_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeach_statement([NotNull] MCSharpParser.Foreach_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.foreach_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeach_statement([NotNull] MCSharpParser.Foreach_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_statement([NotNull] MCSharpParser.While_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_statement([NotNull] MCSharpParser.While_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.do_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDo_statement([NotNull] MCSharpParser.Do_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.do_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDo_statement([NotNull] MCSharpParser.Do_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_statement([NotNull] MCSharpParser.Return_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_statement([NotNull] MCSharpParser.Return_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrow_statement([NotNull] MCSharpParser.Throw_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrow_statement([NotNull] MCSharpParser.Throw_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_statement([NotNull] MCSharpParser.Try_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_statement([NotNull] MCSharpParser.Try_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MCSharpParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MCSharpParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.initialization_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialization_expression([NotNull] MCSharpParser.Initialization_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.initialization_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialization_expression([NotNull] MCSharpParser.Initialization_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.non_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNon_assignment_expression([NotNull] MCSharpParser.Non_assignment_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.non_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNon_assignment_expression([NotNull] MCSharpParser.Non_assignment_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_expression([NotNull] MCSharpParser.Lambda_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_expression([NotNull] MCSharpParser.Lambda_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_list([NotNull] MCSharpParser.Expression_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_list([NotNull] MCSharpParser.Expression_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_expression([NotNull] MCSharpParser.Conditional_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_expression([NotNull] MCSharpParser.Conditional_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.null_coalescing_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull_coalescing_expression([NotNull] MCSharpParser.Null_coalescing_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.null_coalescing_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull_coalescing_expression([NotNull] MCSharpParser.Null_coalescing_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.conditional_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_or_expression([NotNull] MCSharpParser.Conditional_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.conditional_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_or_expression([NotNull] MCSharpParser.Conditional_or_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.conditional_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_and_expression([NotNull] MCSharpParser.Conditional_and_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.conditional_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_and_expression([NotNull] MCSharpParser.Conditional_and_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusive_or_expression([NotNull] MCSharpParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusive_or_expression([NotNull] MCSharpParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusive_or_expression([NotNull] MCSharpParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusive_or_expression([NotNull] MCSharpParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_expression([NotNull] MCSharpParser.And_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_expression([NotNull] MCSharpParser.And_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality_expression([NotNull] MCSharpParser.Equality_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality_expression([NotNull] MCSharpParser.Equality_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelational_expression([NotNull] MCSharpParser.Relational_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelational_expression([NotNull] MCSharpParser.Relational_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.relation_or_type_check"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelation_or_type_check([NotNull] MCSharpParser.Relation_or_type_checkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.relation_or_type_check"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelation_or_type_check([NotNull] MCSharpParser.Relation_or_type_checkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expression([NotNull] MCSharpParser.Shift_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expression([NotNull] MCSharpParser.Shift_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditive_expression([NotNull] MCSharpParser.Additive_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditive_expression([NotNull] MCSharpParser.Additive_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicative_expression([NotNull] MCSharpParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicative_expression([NotNull] MCSharpParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.with_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_expression([NotNull] MCSharpParser.With_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.with_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_expression([NotNull] MCSharpParser.With_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.range_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange_expression([NotNull] MCSharpParser.Range_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.range_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange_expression([NotNull] MCSharpParser.Range_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.pre_step_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPre_step_expression([NotNull] MCSharpParser.Pre_step_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.pre_step_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPre_step_expression([NotNull] MCSharpParser.Pre_step_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.post_step_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPost_step_expression([NotNull] MCSharpParser.Post_step_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.post_step_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPost_step_expression([NotNull] MCSharpParser.Post_step_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expression([NotNull] MCSharpParser.Unary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expression([NotNull] MCSharpParser.Unary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCast_expression([NotNull] MCSharpParser.Cast_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCast_expression([NotNull] MCSharpParser.Cast_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.pointer_indirection_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer_indirection_expression([NotNull] MCSharpParser.Pointer_indirection_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.pointer_indirection_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer_indirection_expression([NotNull] MCSharpParser.Pointer_indirection_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.addressof_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddressof_expression([NotNull] MCSharpParser.Addressof_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.addressof_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddressof_expression([NotNull] MCSharpParser.Addressof_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_expression([NotNull] MCSharpParser.Assignment_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_expression([NotNull] MCSharpParser.Assignment_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_expression([NotNull] MCSharpParser.Primary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_expression([NotNull] MCSharpParser.Primary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.array_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_creation_expression([NotNull] MCSharpParser.Array_creation_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.array_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_creation_expression([NotNull] MCSharpParser.Array_creation_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.array_rank_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_rank_specifier([NotNull] MCSharpParser.Array_rank_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.array_rank_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_rank_specifier([NotNull] MCSharpParser.Array_rank_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.array_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_initializer([NotNull] MCSharpParser.Array_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.array_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_initializer([NotNull] MCSharpParser.Array_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_initializer([NotNull] MCSharpParser.Variable_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_initializer([NotNull] MCSharpParser.Variable_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.primary_no_array_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_no_array_creation_expression([NotNull] MCSharpParser.Primary_no_array_creation_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.primary_no_array_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_no_array_creation_expression([NotNull] MCSharpParser.Primary_no_array_creation_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_access([NotNull] MCSharpParser.Member_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_access([NotNull] MCSharpParser.Member_accessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_expression([NotNull] MCSharpParser.Keyword_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_expression([NotNull] MCSharpParser.Keyword_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.object_or_collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_or_collection_initializer([NotNull] MCSharpParser.Object_or_collection_initializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.object_or_collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_or_collection_initializer([NotNull] MCSharpParser.Object_or_collection_initializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.new_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNew_keyword_expression([NotNull] MCSharpParser.New_keyword_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.new_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNew_keyword_expression([NotNull] MCSharpParser.New_keyword_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.typeof_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeof_keyword_expression([NotNull] MCSharpParser.Typeof_keyword_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.typeof_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeof_keyword_expression([NotNull] MCSharpParser.Typeof_keyword_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.checked_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChecked_expression([NotNull] MCSharpParser.Checked_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.checked_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChecked_expression([NotNull] MCSharpParser.Checked_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.unchecked_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnchecked_expression([NotNull] MCSharpParser.Unchecked_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.unchecked_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnchecked_expression([NotNull] MCSharpParser.Unchecked_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.default_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_keyword_expression([NotNull] MCSharpParser.Default_keyword_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.default_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_keyword_expression([NotNull] MCSharpParser.Default_keyword_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.delegate_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelegate_keyword_expression([NotNull] MCSharpParser.Delegate_keyword_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.delegate_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelegate_keyword_expression([NotNull] MCSharpParser.Delegate_keyword_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.sizeof_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSizeof_keyword_expression([NotNull] MCSharpParser.Sizeof_keyword_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.sizeof_keyword_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSizeof_keyword_expression([NotNull] MCSharpParser.Sizeof_keyword_expressionContext context);
}
