//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MCSharp.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMCSharpListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class MCSharpBaseListener : IMCSharpListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] MCSharpParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] MCSharpParser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_parameter([NotNull] MCSharpParser.Generic_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_parameter([NotNull] MCSharpParser.Generic_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_parameter_list([NotNull] MCSharpParser.Generic_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_parameter_list([NotNull] MCSharpParser.Generic_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_parameters([NotNull] MCSharpParser.Generic_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_parameters([NotNull] MCSharpParser.Generic_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_parameter([NotNull] MCSharpParser.Method_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_parameter([NotNull] MCSharpParser.Method_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_parameter_list([NotNull] MCSharpParser.Method_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_parameter_list([NotNull] MCSharpParser.Method_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_parameters([NotNull] MCSharpParser.Method_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_parameters([NotNull] MCSharpParser.Method_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.indexer_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexer_parameters([NotNull] MCSharpParser.Indexer_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.indexer_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexer_parameters([NotNull] MCSharpParser.Indexer_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] MCSharpParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] MCSharpParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_list([NotNull] MCSharpParser.Argument_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_list([NotNull] MCSharpParser.Argument_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.generic_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_arguments([NotNull] MCSharpParser.Generic_argumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.generic_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_arguments([NotNull] MCSharpParser.Generic_argumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_arguments([NotNull] MCSharpParser.Method_argumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_arguments([NotNull] MCSharpParser.Method_argumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.indexer_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexer_arguments([NotNull] MCSharpParser.Indexer_argumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.indexer_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexer_arguments([NotNull] MCSharpParser.Indexer_argumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.member_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_initializer([NotNull] MCSharpParser.Member_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.member_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_initializer([NotNull] MCSharpParser.Member_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.object_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_initializer([NotNull] MCSharpParser.Object_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.object_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_initializer([NotNull] MCSharpParser.Object_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.element_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_initializer([NotNull] MCSharpParser.Element_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.element_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_initializer([NotNull] MCSharpParser.Element_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollection_initializer([NotNull] MCSharpParser.Collection_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollection_initializer([NotNull] MCSharpParser.Collection_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.anonymous_element_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonymous_element_initializer([NotNull] MCSharpParser.Anonymous_element_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.anonymous_element_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonymous_element_initializer([NotNull] MCSharpParser.Anonymous_element_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.anonymous_object_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonymous_object_initializer([NotNull] MCSharpParser.Anonymous_object_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.anonymous_object_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonymous_object_initializer([NotNull] MCSharpParser.Anonymous_object_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] MCSharpParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] MCSharpParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.parameter_modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_modifier([NotNull] MCSharpParser.Parameter_modifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.parameter_modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_modifier([NotNull] MCSharpParser.Parameter_modifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.class_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_type([NotNull] MCSharpParser.Class_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.class_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_type([NotNull] MCSharpParser.Class_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.type_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_definition([NotNull] MCSharpParser.Type_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.type_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_definition([NotNull] MCSharpParser.Type_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.member_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_definition([NotNull] MCSharpParser.Member_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.member_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_definition([NotNull] MCSharpParser.Member_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.constructor_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor_definition([NotNull] MCSharpParser.Constructor_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.constructor_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor_definition([NotNull] MCSharpParser.Constructor_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.field_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_definition([NotNull] MCSharpParser.Field_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.field_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_definition([NotNull] MCSharpParser.Field_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.property_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_definition([NotNull] MCSharpParser.Property_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.property_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_definition([NotNull] MCSharpParser.Property_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.property_get_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_get_definition([NotNull] MCSharpParser.Property_get_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.property_get_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_get_definition([NotNull] MCSharpParser.Property_get_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.property_set_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_set_definition([NotNull] MCSharpParser.Property_set_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.property_set_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_set_definition([NotNull] MCSharpParser.Property_set_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_definition([NotNull] MCSharpParser.Method_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_definition([NotNull] MCSharpParser.Method_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] MCSharpParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] MCSharpParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] MCSharpParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] MCSharpParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] MCSharpParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] MCSharpParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.code_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_block([NotNull] MCSharpParser.Code_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.code_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_block([NotNull] MCSharpParser.Code_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.additive_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditive_operator([NotNull] MCSharpParser.Additive_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.additive_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditive_operator([NotNull] MCSharpParser.Additive_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.multiplicative_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicative_operator([NotNull] MCSharpParser.Multiplicative_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.multiplicative_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicative_operator([NotNull] MCSharpParser.Multiplicative_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.step_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStep_operator([NotNull] MCSharpParser.Step_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.step_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStep_operator([NotNull] MCSharpParser.Step_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.bitwise_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwise_operator([NotNull] MCSharpParser.Bitwise_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.bitwise_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwise_operator([NotNull] MCSharpParser.Bitwise_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.boolean_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_operator([NotNull] MCSharpParser.Boolean_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.boolean_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_operator([NotNull] MCSharpParser.Boolean_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.shift_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_operator([NotNull] MCSharpParser.Shift_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.shift_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_operator([NotNull] MCSharpParser.Shift_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.equality_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality_operator([NotNull] MCSharpParser.Equality_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.equality_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality_operator([NotNull] MCSharpParser.Equality_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.relation_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation_operator([NotNull] MCSharpParser.Relation_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.relation_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation_operator([NotNull] MCSharpParser.Relation_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] MCSharpParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] MCSharpParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.range_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_operator([NotNull] MCSharpParser.Range_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.range_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_operator([NotNull] MCSharpParser.Range_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.language_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLanguage_function([NotNull] MCSharpParser.Language_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.language_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLanguage_function([NotNull] MCSharpParser.Language_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] MCSharpParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] MCSharpParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_statement([NotNull] MCSharpParser.For_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_statement([NotNull] MCSharpParser.For_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.foreach_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeach_statement([NotNull] MCSharpParser.Foreach_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.foreach_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeach_statement([NotNull] MCSharpParser.Foreach_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] MCSharpParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] MCSharpParser.While_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.do_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDo_statement([NotNull] MCSharpParser.Do_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.do_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDo_statement([NotNull] MCSharpParser.Do_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] MCSharpParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] MCSharpParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.throw_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrow_statement([NotNull] MCSharpParser.Throw_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.throw_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrow_statement([NotNull] MCSharpParser.Throw_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.try_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTry_statement([NotNull] MCSharpParser.Try_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.try_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTry_statement([NotNull] MCSharpParser.Try_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] MCSharpParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] MCSharpParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.initialization_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialization_expression([NotNull] MCSharpParser.Initialization_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.initialization_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialization_expression([NotNull] MCSharpParser.Initialization_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.non_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNon_assignment_expression([NotNull] MCSharpParser.Non_assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.non_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNon_assignment_expression([NotNull] MCSharpParser.Non_assignment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.lambda_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambda_expression([NotNull] MCSharpParser.Lambda_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.lambda_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambda_expression([NotNull] MCSharpParser.Lambda_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_list([NotNull] MCSharpParser.Expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_list([NotNull] MCSharpParser.Expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_expression([NotNull] MCSharpParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_expression([NotNull] MCSharpParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.null_coalescing_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNull_coalescing_expression([NotNull] MCSharpParser.Null_coalescing_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.null_coalescing_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNull_coalescing_expression([NotNull] MCSharpParser.Null_coalescing_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.conditional_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_or_expression([NotNull] MCSharpParser.Conditional_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.conditional_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_or_expression([NotNull] MCSharpParser.Conditional_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.conditional_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_and_expression([NotNull] MCSharpParser.Conditional_and_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.conditional_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_and_expression([NotNull] MCSharpParser.Conditional_and_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusive_or_expression([NotNull] MCSharpParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusive_or_expression([NotNull] MCSharpParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusive_or_expression([NotNull] MCSharpParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusive_or_expression([NotNull] MCSharpParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expression([NotNull] MCSharpParser.And_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expression([NotNull] MCSharpParser.And_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality_expression([NotNull] MCSharpParser.Equality_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality_expression([NotNull] MCSharpParser.Equality_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelational_expression([NotNull] MCSharpParser.Relational_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelational_expression([NotNull] MCSharpParser.Relational_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.relation_or_type_check"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation_or_type_check([NotNull] MCSharpParser.Relation_or_type_checkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.relation_or_type_check"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation_or_type_check([NotNull] MCSharpParser.Relation_or_type_checkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expression([NotNull] MCSharpParser.Shift_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expression([NotNull] MCSharpParser.Shift_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditive_expression([NotNull] MCSharpParser.Additive_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditive_expression([NotNull] MCSharpParser.Additive_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicative_expression([NotNull] MCSharpParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicative_expression([NotNull] MCSharpParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.with_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWith_expression([NotNull] MCSharpParser.With_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.with_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWith_expression([NotNull] MCSharpParser.With_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.range_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_expression([NotNull] MCSharpParser.Range_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.range_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_expression([NotNull] MCSharpParser.Range_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.pre_step_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPre_step_expression([NotNull] MCSharpParser.Pre_step_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.pre_step_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPre_step_expression([NotNull] MCSharpParser.Pre_step_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.post_step_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPost_step_expression([NotNull] MCSharpParser.Post_step_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.post_step_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPost_step_expression([NotNull] MCSharpParser.Post_step_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] MCSharpParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] MCSharpParser.Unary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCast_expression([NotNull] MCSharpParser.Cast_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCast_expression([NotNull] MCSharpParser.Cast_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.pointer_indirection_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer_indirection_expression([NotNull] MCSharpParser.Pointer_indirection_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.pointer_indirection_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer_indirection_expression([NotNull] MCSharpParser.Pointer_indirection_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.addressof_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddressof_expression([NotNull] MCSharpParser.Addressof_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.addressof_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddressof_expression([NotNull] MCSharpParser.Addressof_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_expression([NotNull] MCSharpParser.Assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_expression([NotNull] MCSharpParser.Assignment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression([NotNull] MCSharpParser.Primary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression([NotNull] MCSharpParser.Primary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.array_creation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_creation_expression([NotNull] MCSharpParser.Array_creation_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.array_creation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_creation_expression([NotNull] MCSharpParser.Array_creation_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.array_rank_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_rank_specifier([NotNull] MCSharpParser.Array_rank_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.array_rank_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_rank_specifier([NotNull] MCSharpParser.Array_rank_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.array_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_initializer([NotNull] MCSharpParser.Array_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.array_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_initializer([NotNull] MCSharpParser.Array_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.variable_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_initializer([NotNull] MCSharpParser.Variable_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.variable_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_initializer([NotNull] MCSharpParser.Variable_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.primary_no_array_creation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_no_array_creation_expression([NotNull] MCSharpParser.Primary_no_array_creation_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.primary_no_array_creation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_no_array_creation_expression([NotNull] MCSharpParser.Primary_no_array_creation_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_access([NotNull] MCSharpParser.Member_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_access([NotNull] MCSharpParser.Member_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword_expression([NotNull] MCSharpParser.Keyword_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword_expression([NotNull] MCSharpParser.Keyword_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.object_or_collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_or_collection_initializer([NotNull] MCSharpParser.Object_or_collection_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.object_or_collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_or_collection_initializer([NotNull] MCSharpParser.Object_or_collection_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.new_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNew_keyword_expression([NotNull] MCSharpParser.New_keyword_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.new_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNew_keyword_expression([NotNull] MCSharpParser.New_keyword_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.typeof_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeof_keyword_expression([NotNull] MCSharpParser.Typeof_keyword_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.typeof_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeof_keyword_expression([NotNull] MCSharpParser.Typeof_keyword_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.checked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChecked_expression([NotNull] MCSharpParser.Checked_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.checked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChecked_expression([NotNull] MCSharpParser.Checked_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.unchecked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnchecked_expression([NotNull] MCSharpParser.Unchecked_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.unchecked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnchecked_expression([NotNull] MCSharpParser.Unchecked_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.default_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefault_keyword_expression([NotNull] MCSharpParser.Default_keyword_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.default_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefault_keyword_expression([NotNull] MCSharpParser.Default_keyword_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.delegate_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelegate_keyword_expression([NotNull] MCSharpParser.Delegate_keyword_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.delegate_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelegate_keyword_expression([NotNull] MCSharpParser.Delegate_keyword_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MCSharpParser.sizeof_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeof_keyword_expression([NotNull] MCSharpParser.Sizeof_keyword_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MCSharpParser.sizeof_keyword_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeof_keyword_expression([NotNull] MCSharpParser.Sizeof_keyword_expressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
